server:
  port: 8083

db:
  username: postgres
  password: postgres
  name: microservices_app
  url: localhost
  port: 5432
  schema: payment
spring:
  application:
    name: PAYMENT_SERVICE
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${db.url}:${db.port}/${db.name}?currentSchema=${db.schema}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 1.0
    placeholder-replacement: false
    user: ${db.username}
    password: ${db.password}
    url: jdbc:postgresql://${db.url}:${db.port}/${db.name}?currentSchema=${db.schema}
    schemas: ${db.schema}