publisher:
  success:
    topic: com.indivara.logging.saving.data.success
    publishFixedRateInMilliseconds: 10
    archiveFixedRateInMilliseconds: 3600000
    limitPerFetch: 5
spring:
  kafka:
    bootstrap-servers: 192.168.56.1:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer