server:
  port: 8085
service:
  consumer:
    topic: com.indivara.logging.saving.data.success
db:
  username: postgres
  password: postgres
  name: microservices_app
  url: localhost
  port: 5432
  schema: logging
spring:
  application:
    name: LOGGING-SERVICE
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://${db.url}:${db.port}/${db.name}?currentSchema=${db.schema}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${db.schema}
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-version: 1.0
    placeholder-replacement: false
    user: ${db.username}
    password: ${db.password}
    url: jdbc:postgresql://${db.url}:${db.port}/${db.name}?currentSchema=${db.schema}
    schemas: ${db.schema}
  kafka:
    bootstrap-servers: 192.168.56.1:9092
    consumer:
      group-id: com.indivara.loggingservice
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
